#!/bin/bash
# Installs and configures HAproxy on lb-01 server.

# Exit on any error
set -e

# Update package list and install HAProxy
apt-get update
apt-get install -y haproxy

# Configure HAProxy
HAPROXY_CONFIG="/etc/haproxy/haproxy.cfg"
echo "# Global settings
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    option  httplog
    option  dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

# Frontend configuration
frontend http_front
    bind *:80
    default_backend http_back

# Backend configuration
backend http_back
    balance roundrobin
    server web01 530838-web-01 54.90.30.26:80 check
    server web02 530838-web-02 52.86.91.47:80 check

# Enable HAProxy stats
listen stats
    bind *:8404
    stats enable
    stats uri /
    stats hide-version
    stats auth admin:password" > "$HAPROXY_CONFIG"

# Enable and start HAProxy service
systemctl enable haproxy
systemctl restart haproxy

# Verify configuration
haproxy -c -f "$HAPROXY_CONFIG"

# Ignore SC2154 for shellcheck purposes (custom rule handling)
# shellcheck disable=SC2154

