#!/usr/bin/env bash
# A Bash script that configures a server Nginx to be running, and listening on port 80 of all the server’s active IPv4 IPs
sudo apt-get update -y
sudo apt-get install -y nginx

sudo sed -i 's/^listen .*/listen 80 default_server;/' /etc/nginx/sites-available/default

sudo systemcl enable nginx
sudo systemcl start nginx
